"""Inference domain models."""

from pydantic import BaseModel, Field, field_validator


class InferenceRequest(BaseModel):
    """Represents a request for executing local model inference."""

    model: str = Field(
        ...,
        description="The target model name (e.g. 'llama3-8b').",
    )
    prompt: str = Field(
        ...,
        description="The prompt input text to send to the model.",
    )

    @field_validator("model", "prompt")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        """Validate that the string is not empty or whitespace-only."""
        if not v.strip():
            raise ValueError("Value cannot be empty or whitespace-only.")
        return v.strip()


class InferenceResponse(BaseModel):
    """Represents the response generated by executing local model inference."""

    model: str = Field(
        ...,
        description="The name of the model that generated the response.",
    )
    response: str = Field(
        ...,
        description="The text content generated by the model.",
    )

    @field_validator("model")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        """Validate that the model name is not empty or whitespace-only."""
        if not v.strip():
            raise ValueError("Model name cannot be empty or whitespace-only.")
        return v.strip()
