"""Pydantic schemas for OpenAI REST API specification compliance."""

from time import time

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Message object inside a Chat Completion request/response."""

    role: str = Field(
        description="The role of the author of this message (system, user, assistant)."
    )
    content: str = Field(description="The contents of the message.")
    name: str | None = Field(default=None, description="Optional name for the author.")


class ChatCompletionRequest(BaseModel):
    """Request payload for POST /v1/chat/completions."""

    model: str = Field(description="ID of the model to use.")
    messages: list[ChatMessage] = Field(
        description="A list of messages comprising the conversation so far."
    )
    stream: bool = Field(
        default=False, description="If set, partial message deltas will be sent as SSE."
    )
    temperature: float | None = Field(default=1.0, description="Sampling temperature.")
    max_tokens: int | None = Field(
        default=None, description="Maximum number of tokens to generate."
    )
    split_inference: bool = Field(
        default=False, description="Enable split inference local boundary mode."
    )


class CompletionUsage(BaseModel):
    """Usage statistics for the completion request."""

    prompt_tokens: int = Field(default=0, description="Number of tokens in the prompt.")
    completion_tokens: int = Field(
        default=0, description="Number of tokens in the generated completion."
    )
    total_tokens: int = Field(default=0, description="Total number of tokens used in the request.")


class ChatCompletionResponseChoice(BaseModel):
    """Choice object in a Chat Completion response."""

    index: int = Field(default=0, description="The index of the choice in the list of choices.")
    message: ChatMessage = Field(description="A chat completion message generated by the model.")
    finish_reason: str | None = Field(
        default="stop", description="The reason the model stopped generating tokens."
    )


class ChatCompletionResponse(BaseModel):
    """Response payload for POST /v1/chat/completions (non-streaming)."""

    id: str = Field(description="A unique identifier for the chat completion.")
    object: str = Field(
        default="chat.completion",
        description="The object type, which is always 'chat.completion'.",
    )
    created: int = Field(
        default_factory=lambda: int(time()),
        description="The Unix timestamp (in seconds) of creation.",
    )
    model: str = Field(description="The model used for the chat completion.")
    choices: list[ChatCompletionResponseChoice] = Field(
        description="A list of chat completion choices."
    )
    usage: CompletionUsage = Field(
        default_factory=CompletionUsage, description="Usage statistics for the completion request."
    )


class ChatCompletionChunkDelta(BaseModel):
    """Delta object in a Chat Completion chunk."""

    role: str | None = Field(default=None, description="The role of the author of this message.")
    content: str | None = Field(default=None, description="The contents of the chunk delta.")


class ChatCompletionChunkChoice(BaseModel):
    """Choice object in a Chat Completion chunk."""

    index: int = Field(default=0, description="The index of the choice in the list of choices.")
    delta: ChatCompletionChunkDelta = Field(description="A chunk delta generated by the model.")
    finish_reason: str | None = Field(
        default=None, description="The reason the model stopped generating tokens."
    )


class ChatCompletionChunk(BaseModel):
    """Response payload for POST /v1/chat/completions (streaming chunk)."""

    id: str = Field(description="A unique identifier for the chat completion chunk.")
    object: str = Field(
        default="chat.completion.chunk",
        description="The object type, which is always 'chat.completion.chunk'.",
    )
    created: int = Field(
        default_factory=lambda: int(time()),
        description="The Unix timestamp (in seconds) of creation.",
    )
    model: str = Field(description="The model used for the chat completion.")
    choices: list[ChatCompletionChunkChoice] = Field(
        description="A list of chat completion chunk choices."
    )


class ModelObject(BaseModel):
    """Model metadata object in GET /v1/models response."""

    id: str = Field(description="The model identifier.")
    object: str = Field(default="model", description="The object type, which is always 'model'.")
    created: int = Field(
        default=1700000000,
        description="The Unix timestamp (in seconds) when the model was created.",
    )
    owned_by: str = Field(
        default="public-intelligence", description="The organization that owns the model."
    )


class ModelListResponse(BaseModel):
    """Response payload for GET /v1/models."""

    object: str = Field(default="list", description="The object type, which is always 'list'.")
    data: list[ModelObject] = Field(default_factory=list, description="List of model objects.")
