#!/usr/bin/env bash
#
# Installs a pre-push hook that runs scripts/verify.sh before any push.
#
# Run once after cloning:  ./scripts/install-hooks.sh
#
# Git hooks live in .git/, which is not tracked, so this cannot be checked in
# directly and every clone has to opt in. The hook exists because CI is the real
# gate but runs ~90 seconds after you have already pushed and said "done" -- the
# feedback arrives after the claim. This moves it before.
#
# Bypass for a genuine emergency:  git push --no-verify

set -euo pipefail
cd "$(dirname "$0")/.." || exit 1
REPO_ROOT="$(pwd)"

install_one() {
    local repo_dir="$1" label="$2"
    local hooks_dir
    hooks_dir="$(git -C "$repo_dir" rev-parse --git-path hooks)"
    hooks_dir="$repo_dir/$hooks_dir"
    # Submodule .git is a file pointing into the parent's modules/ dir; rev-parse
    # already resolves that, but the path it returns may be absolute.
    [[ "$hooks_dir" = /* ]] || hooks_dir="$repo_dir/$hooks_dir"
    hooks_dir="$(cd "$(dirname "$hooks_dir")" && pwd)/$(basename "$hooks_dir")"
    mkdir -p "$hooks_dir"

    cat > "$hooks_dir/pre-push" <<EOF
#!/usr/bin/env bash
# Generated by scripts/install-hooks.sh -- edit that, not this.
echo "pre-push: running scripts/verify.sh ($label)"
exec "$REPO_ROOT/scripts/verify.sh"
EOF
    chmod +x "$hooks_dir/pre-push"
    echo "  installed: $label -> $hooks_dir/pre-push"
}

echo "Installing pre-push hooks:"
install_one "$REPO_ROOT" "root"
for sub in Node Scheduler website; do
    [ -d "$REPO_ROOT/$sub/.git" ] || [ -f "$REPO_ROOT/$sub/.git" ] || continue
    install_one "$REPO_ROOT/$sub" "$sub"
done

echo
echo "Done. Every push now runs the full gate first."
echo "Emergency bypass: git push --no-verify"
