"""Inference domain models."""

from pydantic import BaseModel, Field, field_validator


class InferenceRequest(BaseModel):
    """Represents a request for executing local model inference."""

    model: str = Field(
        ...,
        description="The target model name (e.g. 'llama3-8b').",
    )
    prompt: str = Field(
        ...,
        description="The prompt input text to send to the model.",
    )
    stream: bool = Field(
        default=False,
        description="Whether to stream the response chunks.",
    )
    worktree_target_branch: str | None = Field(
        default=None,
        description="Optional branch name to map the query to a clean git worktree.",
    )

    @field_validator("model", "prompt")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        """Validate that the string is not empty or whitespace-only."""
        if not v.strip():
            raise ValueError("Value cannot be empty or whitespace-only.")
        return v.strip()

    @field_validator("worktree_target_branch")
    @classmethod
    def validate_branch_name(cls, v: str | None) -> str | None:
        """Validate that the branch name is not empty or whitespace-only if provided."""
        if v is not None and not v.strip():
            raise ValueError("Branch name cannot be empty or whitespace-only.")
        return v.strip() if v is not None else None


class InferenceResponse(BaseModel):
    """Represents the response generated by executing local model inference."""

    model: str = Field(
        ...,
        description="The name of the model that generated the response.",
    )
    response: str = Field(
        ...,
        description="The text content generated by the model.",
    )

    @field_validator("model")
    @classmethod
    def validate_non_empty(cls, v: str) -> str:
        """Validate that the model name is not empty or whitespace-only."""
        if not v.strip():
            raise ValueError("Model name cannot be empty or whitespace-only.")
        return v.strip()
